### ISSUE TITLE
Не оптимизированный поиск на странице "Соревнования"

### ISSUE THREAD

**Issue by ITilyaGO** [lexxyar/yarfso#1]
Страница зависает при быстром вводе символов в строку поиска. ([Здесь](http://wp.lexxsoft.ru/соревнования/))
Чем больше действий(написать/стереть символ) произведено в строке поиска там сильнее зависание при каждом новом.
Предположительно - Событие поиска вызывается при вводе символа, так как процесс получения списка довольно тяжелый, из-за этого страница зависает.
Предлагаю решение - Вызывать событие поиска только после бездействия после ввода последнего символа ~500мс.

**Comment by lexxyar** [comment]
Поиск происходит на клиенте, т.к. данные с оргео получаются 1 раз. Прикручу решение с задержкой, возможно ситуация будет выглядеть лучше.

**Comment by ITilyaGO** [comment]
Как я понимаю с оргео данные приходят на сайт, записываются в БД, с сайта на клиент, и везде данные посылаются один раз. Поиск происходит на клиенте(То есть при помощи браузера не отправляя каждый раз запросы на БД сайта)?
