### ISSUE TITLE
Невозможно посмотреть информацию кого ты оплачиваешь, если нажать на статус "В обработке"

### ISSUE THREAD

**Issue by ITilyaGO** [lexxyar/yarfso#10]
При нажатии на статус "В обработке" вместо показания QR кода, необходимо переводить на ту же страницу оплаты с тем же списком выбранных участников что была при генерации QR кода.

**Comment by lexxyar** [comment]
_В ОБРАБОТКЕ – Выводится, если у участника заполнено значение «Идентификатор QR-кода СБП» но не установлен флаг «Оплачено», при нажатии позволяет вывести сгенерированный ранее QR-код для оплаты через систему СБП_
