### ISSUE TITLE
Отсутствует фильтрация по разным полям списка участников

### ISSUE THREAD

**Issue by ITilyaGO** [lexxyar/yarfso#11]
Поиска по фамилии недостаточно, нужно сделать возможность поиска по любому из полей, или по определенному полю. Так же искать не только варианты начинающиеся с какого-то текста но и содержащие текст.
Необходима возможность показать всех участников только одной команды,  заявителя, группы, допуску(всех у кого есть допуск), полу.
И возможность комбинировать эти фильтры.

# Предложения 

Для удобства поиска во всех Dropdown списках в него можно поставить курсор и начать писать - в списке останутся только 
скачала начинающиеся с этого текста варианты а потом и содержащие вбитый текст.
## Строка поиска
У строки поиска Dropdown список с выбором поля для поиска, и "Все" режим - поиск по всем полям.
В таком порядке -
- Все
- Фамилия, имя
- Команда
- Заявка
- Пол
- Год
- Квалификация
- Группа
- Дни участия
- Сумма
- Оплата
- 
## Фильтрация по столбцам
Cделать над каждым столбцом Dropdown список в котором будет пункт - Нет и все возможные варианты в этом столбце.
Пример - Dropdown над полем группы содержит
- Нет 
- Ж10
- Ж12
- Ж14
- Ж16
- Ж18
- Ж21
- М10
- М12
- М14
- М16
- М18
- М21

Пример - Dropdown над полем заявка содержит 
- Нет 
- Bannikova Elena [751889]
- Богопольская Елена [709284]
- Грибанова Татьяна [751137]
- Мендель Владимир [756586]
- Романов Александр [755763]
- ... По алфовиту

**Comment by lexxyar** [comment]
Вопрос про этот поиск на странице Соревнования?
<img width="317" alt="Снимок экрана 2022-11-17 в 09 36 03" src="https://user-images.githubusercontent.com/23395412/202374010-5d05ee03-ecee-4260-923e-29886db001fc.png">

**Comment by ITilyaGO** [comment]
Да, про этот. 
Он плохо работает и не позволяет отфильтровать участников по команде.
![image](https://user-images.githubusercontent.com/42610063/202438837-093dd7b2-2bfb-481e-ab60-84317ababb5f.png)
![image](https://user-images.githubusercontent.com/42610063/202439038-46efb9b0-bd95-4d7a-8f6c-d196d4aa1437.png)
Как минимум нужно сделать возможность отдельно отфильтровать по команде или заявке.
