### ISSUE TITLE
В админской вкладке "Участники соревнований" не видно ID заявки на оргео

### ISSUE THREAD

**Issue by ITilyaGO** [lexxyar/yarfso#12]
Если такая информация имеется в базе "Участники соревнований" то [Тут](http://wp.lexxsoft.ru/wp-admin/admin.php?page=participants) нужно отображать ее хотя-бы в режиме чтения. Так же не помешает видеть ID сущности если в дальнейшем его нужно будет использовать при генерации QR кода оплаты в качестве дополнения примечания.

**Comment by lexxyar** [comment]
Добавлю вывод оргео ID для соревнования в формате <Название соревнования> [<Номер оргео>]

**Comment by ITilyaGO** [comment]
Речь идет про эти ID заявок с Оргео, если это они
![image](https://user-images.githubusercontent.com/42610063/202445543-6b11853d-65f2-45c6-8a02-d0b9cbd9fb52.png)
И хотелось бы добавить их отдельным столбцом.

**Comment by ITilyaGO** [comment]
Вы добавили ID соревнований а не заявки.
На скриншоте выше ясно показано про какой ID шла речь.
