### ISSUE TITLE
Отсутствует страница с отчётами

### ISSUE THREAD

**Issue by ITilyaGO** [lexxyar/yarfso#13]
![image](https://user-images.githubusercontent.com/42610063/202461200-cd60b156-11a3-419a-b7d5-2d363fe95f99.png)

**Comment by lexxyar** [comment]
(c) Алексей: Я думаю что пока никто не будет морочиться забиванием в систему результатов. Поэтому давай пока ограничимся одним отчетом. 	Список спортсменов со сроками действия квалификации, страховки и медицинского допуска;
