### ISSUE TITLE
Ошибка при отправке документов на адрес федерации

### ISSUE THREAD

**Issue by ITilyaGO** [lexxyar/yarfso#14]
Ошибка происходит после загрузки файла и нажатия кнопки отправить.
![image](https://user-images.githubusercontent.com/42610063/202465595-c474a0fe-607a-4a6b-9eb0-cef1b8d0f7c4.png)
![image](https://user-images.githubusercontent.com/42610063/202465614-e41036ba-ffff-42b0-9129-bfd5ac243602.png)
![image](https://user-images.githubusercontent.com/42610063/202466171-c2f9b929-ff7d-49ff-b533-1ea45faef6dd.png)

**Comment by ITilyaGO** [comment]
Ошибка осталась.

**Comment by lexxyar** [comment]
Ошибка связана с настройками сервиса отправки на сервере
