### ISSUE TITLE
Необходимые изменения страницы оплаты

### ISSUE THREAD

**Issue by ITilyaGO** [lexxyar/yarfso#4]
На странице оплаты, кнопку оплатить надо поместить по центру места под QR код.
После нажатия кнопка исчезает, вместо нее появляется QR код.
После оплаты пользователем, QR код пропадает, вместо него появляется надпись _Оплачено_ и _Вернуться к списку участников_
Кнопка _Вернуться к списку участников_ должна возвращать пользователя на страницу соревнований с Query-параметром оплаченных соревнований

Шрифт кнопок на ваш выбор

Кнопка _Оплатить_ должна иметь примерно такой вид и размер
Расположение по центу окна QR кода
Цвет фона `#12103A`
![image](https://user-images.githubusercontent.com/42610063/202283078-b85b6948-f16c-48a2-bd5e-f2283287e306.png)

Надпись _Оплачено_ должна иметь примерно такой вид и размер
Кнопка _Вернуться к списку участников_
Расположение по центу окна QR кода
Цвет фона _Оплачено_ `#08A652`
Цвет фона _Вернуться к списку участников_ `#6B6B6B`
![image](https://user-images.githubusercontent.com/42610063/202285800-6dee041f-eb89-4ec4-96ea-6e9b12a45731.png)

Лого в SVG
![sbp_logo](https://user-images.githubusercontent.com/42610063/202283390-cbb63011-1007-480c-b8be-88fe3f5b8ff6.svg)

**Comment by lexxyar** [comment]
Описания интерфейса в постановке нет. Доработка потребует порядка 16ч времени и дополнительную оплату.
