### ISSUE TITLE
На маленьком разрешении экрана правая часть таблицы на странице "Соревнования" становится не видна

### ISSUE THREAD

**Issue by ITilyaGO** [lexxyar/yarfso#6]
При использовании Google Chrome и мониторе разрешением меньше 1024 пикселя в ширину, либо уменьшении размеров окна браузера - правая часть таблицы участников становится не видна, и промотать вправо тоже нет возможности.
Нужна возможность промотать в бок при вылезании таблицы за край отображаемой области. Либо автоматическая коррекция размеров колонок, но в таком случае таблица может превратиться в кашу на некоторых разрешениях.

**Comment by lexxyar** [comment]
Добавлена прокрутка
