### ISSUE TITLE
Невозможно отметить галочкой пользователей с разных страниц списка участников на странице "Соревнования"

### ISSUE THREAD

**Issue by ITilyaGO** [lexxyar/yarfso#7]
При оплате больших команд участников невозможно будет выбрать всю команду.
Нужно добавить возможность изменения количества отображаемых участников на странице.
И сохранение выделенных участников при перелистывании страницы.
Так же при выставлении галочки выделить всех должны выделяться все найденные участники(Появляется баг что любой может выбрать всех и сгенерировать QR код, и уже ни кто не сможет оплатить себя).

**Comment by lexxyar** [comment]
Не понял про баг.

**Comment by ITilyaGO** [comment]
Этот баг был описан позже #9
Дальнейшие его обсуждения там
