### ISSUE TITLE
Невозможно оплатить участника если кто то случайно выбрал его и несколько других участников, сгенерировав QR код.

### ISSUE THREAD

**Issue by ITilyaGO** [lexxyar/yarfso#9]
Если выбрать несколько участников, сгенерировать на них QR код, и не оплатить, то уже нет возможности изменить список оплачиваемых участников по этому QR коду. И если человек случайно или намеренно выберет какое-то количество участников которых нужно оплатить раздельно, и создаст на них код оплаты, они не смогут оплатить себя без оплаты других.

КРИТИЧЕСКОЕ, ВАРИАНТЫ РЕШЕНИЯ НЕОБХОДИМО ОБСУДИТЬ!

**Comment by lexxyar** [comment]
В постановке нет данного требования. В устной беседе с Алексеем обговорили, что это на совести пользователя. Доработка потребует дополнительную оплату

**Comment by ITilyaGO** [comment]
Если человек случайно выберет дополнительного участника и сгенерирует на него QR код, поправить это можно только вручную из админской панели. Я считаю это не правильно, тоже обсужу с Алексеем.
